language: scala

scala:
  - 2.12.11

jdk: openjdk8

import:
- source: ".travis/release-flow.yml"
  if: branch = master and type = push

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    - GITHUB_REPO="github.com/adrian-shyshkovskyi/scala-hello-world.git"